version: '3.8'
services:
  postgres:
    container_name: db
    image: postgres:latest
    restart: always
    ports:
      - '${PG_PORT:-5432}:${PG_INTERNAL_PORT:-5432}'
    env_file: ./.env
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS

